Add checkSchedule route to API documentation
SENG499-S22-Company3/shared pull request #32
Opened 2022-07-15 21:30 UTC by BrodyGimson

@treavorgagne would appreciate a once over as I am not familiar with the format like you are before I make a PR. Also any suggestions would be much appreciated!

# GraphQL Schema Change Request

1. Update the [Google Document](https://docs.google.com/document/d/1x6KEY6Kw-w27Hrgs4ZayMnQelcrhUBcx4dytABuLY2k/edit) to reflect the changes in the GraphQL schema.
2. Make the schema changes.
3. Receive approval from backend of company 3 and company 4.
4. Merge changes and ping backend and frontend from companies.

## General Comments

### Why

Need to add schema for checkSchedule route to validate manually editted schedules

### Stakeholders

- [ ] Company 1
  - [ ] Backend
  - [ ] Frontend
  - [ ] Algorithm 1
  - [ ] Algorithm 2
- [ ] Company 2
  - [ ] Backend
  - [ ] Frontend
  - [ ] Algorithm 1
  - [ ] Algorithm 2

2022-07-15 22:26 UTC, treavorgagne requested changes
Looks really good. I think the only thing that's missing is 400 requests.

2022-07-15 22:36 UTC, BrodyGimson commented
> Looks really good. I think the only thing that's missing is 400 requests.

Added a 400 status code in

2022-07-15 23:24 UTC, treavorgagne approved these changes

2022-07-16 04:21 UTC, aomi approved these changes

2022-07-18 22:31 UTC, treavorgagne approved these changes

2022-07-18 22:32 UTC, merged